{{- define "troubleshoot.preflights" -}}
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: slackernews-preflight
spec:
  collectors:      
    - clusterInfo: {}
    - clusterResources: {}
    - http:
        collectorName: slack
        get:
          url: https://api.slack.com/methods/api.test
  analyzers:
    - distribution:
        checkName: Is this a supported Kubernetes distribution?
        outcomes:
          - fail:
              when: "== openShiftt"
              message: OpenShift is a supported distribution
          - pass:
              message: You are instaling to a supported distribution
    - textAnalyze:
        checkName: Slack Accessible
        fileName: slack.json
        regex: '"status": 200,'
        outcomes:
          - pass:
              when: "true"
              message: "Can access the Slack API"
          - fail:
              when: "false"
              message: |
                Cannot access the Slack API. Check your firewall settings,
                network policies, and the [Slack status
                page](https://status.slack.com).

{{- end -}}
