---
apiVersion: v1
kind: Secret
metadata:
  name: slackernews-preflight
  labels: 
    troubleshoot.sh/kind: preflight
stringData:
  preflight.yaml: |- {{- include "troubleshoot.preflights" . | nindent 4 }}
