---
apiVersion: v1
kind: Secret
metadata:
  name: slackernews-preflight
  labels: 
    troubleshoot.sh/kind: preflight
stringData:
  preflight.yaml: |- {{- include "troubleshoot.preflights" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: slackernews-support-bundle
  labels: 
    troubleshoot.sh/kind: support-bundle
stringData:
  support-bundle-spec: |- {{- include "troubleshoot.supportBundle" . | nindent 4 }}
