{{- define "troubleshoot.supportBundle" -}}
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: {{ include "common.names.name" . }}-support-bundle
spec:
  collectors:      
    - clusterInfo: {}
    - clusterResources: {}
    - http:
        collectorName: slack
        get:
          url: https://api.slack.com/methods/api.test
  analyzers:
    - textAnalyze:
        checkName: Slack Accessible
        fileName: slack.json
        regex: '"status": 200,'
        outcomes:
          - pass:
              when: "true"
              message: "Can access the Slack API"
          - fail:
              when: "false"
              message: |
                Cannot access the Slack API. Check your firewall settings,
                network policies, and the [Slack status
                page](https://status.slack.com).

{{- end -}}
