apiVersion: batch/v1
kind: CronJob
metadata:
  name: provide-license-metrics
spec:
  schedule: "0 0 * * *"  # Runs at midnight every day
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-container
            image: curlimages/curl  # Using the official curl image
            command:
            - /bin/sh
            - -c
            - >
              curl http://slackernews:3000/api/metrics
          restartPolicy: OnFailure

