name: release

on:
  push:
    tags:
    - "v*.*.*"
env:
  REGISTRY: index.docker.io

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      tags: ${{ steps.web-meta.outputs.tags }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Extract metadata (tags, labels) for web image
        id: web-meta
        uses: docker/metadata-action@v4
        with:
          tags: |
                type=sha,format=long
                type=schedule
                type=semver,pattern={{version}}
                type=ref,event=branch
                type=ref,event=tag
                type=ref,event=pr
          images: ${{ env.REGISTRY }}/${{ secrets.REGISTRY_NAMESPACE }}/slackernews-web

      - uses: int128/docker-build-cache-config-action@v1
        id: cache
        with:
          image: ghcr.io/${{ github.repository }}/cache

      - name: Build web image
        uses: docker/build-push-action@v4
        with:
          context: ./slackernews
          tags: ${{ steps.web-meta.outputs.tags }}
          labels: ${{ steps.web-meta.outputs.labels }}
          file: ./deploy/Dockerfile.web
          push: true
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}

  release:
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
        path: source

      - uses: actions/checkout@v4
        repository: shortrib-labs/charts
        path: repository

      - id: get_version
        uses: battila7/get-version-action@v2

      - uses: azure/setup-helm@v1
        with:
          version: "3.9.0"
        id: install

      - name: Update the values.yaml with the image path
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: 'chart/slackernews/values.yaml'
          find: '$IMAGE'
          replace: '${{ secrets.REGISTRY_NAMESPACE }}/slackernews-web:${{ steps.get_version.outputs.version-without-v }}'
          regex: false

      - name: Update the values.yaml with the nginx image path
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: 'chart/slackernews/values.yaml'
          find: '$NGINX_IMAGE'
          replace: '${{ secrets.REGISTRY_NAMESPACE }}/slackernews-nginx:${{ steps.get_version.outputs.version-without-v }}'
          regex: false

      - id: package-helm-chart
        run: |
          helm -u package source/chart/slackernews  \
            --app-version=${{ steps.get_version.outputs.version-without-v }} \
            --version=${{ steps.get_version.outputs.version-without-v }} \
            -d ./repository

      - id: index-chart-repo
        run: |
          helm repo index repository --url https://shortrib-labs.github.io/charts

      - id: commit-repostiory
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: repository
          commit_message: "Release chart version ${{ steps.get_version.outputs.version-without-v }}"
