name: release

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      tags: ${{ steps.web-meta.outputs.tags }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Extract metadata (tags, labels) for web image
        id: web-meta
        uses: docker/metadata-action@v4
        with:
          tags: |
                type=sha,format=long
                type=schedule
                type=semver,pattern={{version}}
                type=ref,event=branch
                type=ref,event=tag
                type=ref,event=pr
          images: ${{ secrets.REGISTRY_NAMESPACE }}/slackernews-web

      - uses: int128/docker-build-cache-config-action@v1
        id: cache
        with:
          image: ghcr.io/${{ github.repository }}/cache

      - name: Build web image
        uses: docker/build-push-action@v4
        with:
          context: ./slackernews
          tags: ${{ steps.web-meta.outputs.tags }}
          labels: ${{ steps.web-meta.outputs.labels }}
          file: ./deploy/Dockerfile.web
          push: true
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}

  release:
    runs-on: ubuntu-22.04
    needs:
      - build
    permissions:
      contents: write
    outputs:
      version: ${{ steps.get_version.outputs.version-without-v }} 
      release-sequence: ${{ steps.release.outputs.release-sequence }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: source

      - uses: actions/checkout@v4
        with:
          repository: shortrib-labs/charts
          path: repository
          ref: main
          token: ${{ secrets.PRIVILEGED_GITHUB_TOKEN }}


      - id: get_version
        uses: battila7/get-version-action@v2

      - uses: azure/setup-helm@v1
        with:
          version: "3.9.0"
        id: install

      - name: Update the values.yaml with the image path
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: 'chart/slackernews/values.yaml'
          find: '$IMAGE'
          replace: '${{ secrets.REGISTRY_NAMESPACE }}/slackernews-web:${{ steps.get_version.outputs.version-without-v }}'
          regex: false

      - name: Update the values.yaml with the nginx image path
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: 'chart/slackernews/values.yaml'
          find: '$NGINX_IMAGE'
          replace: '${{ secrets.REGISTRY_NAMESPACE }}/slackernews-nginx:${{ steps.get_version.outputs.version-without-v }}'
          regex: false

      - id: package-helm-chart
        run: |
          helm package -u source/chart/slackernews  \
            --app-version=${{ steps.get_version.outputs.version-without-v }} \
            --version=${{ steps.get_version.outputs.version-without-v }} \
            -d ./repository

      # Release the chart using the Replicated Platform
      - name: Create the unstable release
        uses: replicatedhq/replicated-actions/create-release@v1
        id: release
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          chart: ./repository/slackernews-${{ steps.get_version.outputs.version-without-v }}.tgz
          version: ${{ needs.release.outputs.version }}
 
  unstable:
    runs-on: ubuntu-22.04
    needs: 
      - release
    steps:
      # Release the chart using the Replicated Platform
      - name: Promote the unstable release to beta
        uses: replicatedhq/replicated-actions/promote-release@v1
        id: release
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          release-sequence: ${{ needs.unstable.outputs.release-sequence }}
          channel-to: unstable
          release-version: ${{ needs.release.outputs.version }}

  beta:
    runs-on: ubuntu-22.04
    needs: 
      - release
      - unstable
    steps:
      # Release the chart using the Replicated Platform
      - name: Promote the unstable release to beta
        uses: replicatedhq/replicated-actions/promote-release@v1
        id: release
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          release-sequence: ${{ needs.unstable.outputs.release-sequence }}
          channel-to: beta
          release-version: ${{ needs.release.outputs.version }}

  stable:
    runs-on: ubuntu-22.04
    needs: 
      - release
      - beta
    permissions:
      contents: write
    steps:
      - name: Promote the release to stable
        uses: replicatedhq/replicated-actions/promote-release@v1
        id: release
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          release-sequence: ${{ needs.unstable.outputs.release-sequence }}
          channel-to: stable
          release-version: ${{ needs.release.outputs.version }}

      # Updates the old chart repository to locate the new chart releases
      - id: index-chart-repo
        run: |
          helm repo index repository --url https://shortrib-labs.github.io/charts --merge repository/index.yaml

      - id: commit-repostiory
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: repository
          commit_message: "Release chart version ${{ steps.get_version.outputs.version-without-v }}"

